### ISSUE TITLE
requires Ruby 2.x

### ISSUE THREAD

**Issue by ghukill** [emory-libraries-ecds/teifacsimile-to-jekyll#1]
Looks like maybe the "double splat" operator [here](https://github.com/emory-libraries-ecds/teifacsimile-to-jekyll/blob/master/bin/jekyllimport_teifacsimile#L28) requires Ruby 2.x:

http://stackoverflow.com/questions/18289152/what-does-a-double-splat-operator-do/18289216#18289216

Once we upgraded the ruby version, worked like a charm.  Realize it's not a bug per say, but thought it might be worth mentioning somewhere.  Some plain Ubuntu installs still come with Ruby 1.9.x it seems.

**Comment by rlskoeser** [comment]
Thanks for this note (and sorry for the delay).  I'll add a prominent comment to the readme.
